all:
  hosts:
  children:
    agent:
      hosts:
        185.62.103.120:
          ansible_user: centos
          metric_buffer_size: 10000
          namespace: 0c2b8049-976a-4de7-8e76-74d300dcdac9
          project: 'fd09ff8c-d35a-48e3-b8f3-fbbfd53029b6'
          supplier_id: 0c2b8049-976a-4de7-8e76-74d300dcdac9
#          endpoint: http://87.239.107.8/v1
          endpoint: http://172.16.110.170/private-consumer/v1

